title: Song Huang's Homepage
page-top-title: 黄淞
top-section-bg-text: Subject to the constraints, and maximize the utility.
home-subtitle: 黄淞&ensp;|&ensp;Song Huang
copyright-text: '&copy; All Rights Reserved.'
